class DouyinException(Exception): ...


class UpsertUserError(DouyinException): ...


class UserNotFoundError(DouyinException): ...


class FetchUserPostVideosError(DouyinException): ...


class UpsertVideoError(DouyinException): ...
